export const GETPOSTS_LOADING = "GETPOSTS_LOADING";
export const GETPOSTS_SUCCESS = "GETPOSTS_SUCCESS";
export const GETPOSTS_ERROR = "GETPOSTS_ERROR";
export const ADDPOST = "ADDPOST";
export const UPDATEPOST = "UPDATEPOST";
export const DELETEPOST = "DELETEPOST";